spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/petclinic}
spring.datasource.username=${DB_USERNAME:petclinic}
spring.datasource.password=${DB_PASSWORD:petclinic}

spring.jpa.hibernate.ddl-auto=none
spring.flyway.locations=classpath:db/migration
